In [2]:
import numpy as np

In [3]:
#vector/1d array
a = np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [4]:
#matrix/2d array
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
 #tensor/3d array
c = np.array( [ [ [1,2],[3,4] ] , [ [5,6],[7,8] ] ] )
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
#data type in numpy array
print( np.array( [0,2,3] , dtype=str ) )
print( np.array( [0,2,3] , dtype=bool ) )
print( np.array( [0,2,3] , dtype=float ) )

['0' '2' '3']
[False  True  True]
[0. 2. 3.]


In [10]:
#same as range function in python
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [11]:
#reshaping numpy array first argument=row,second argument=col
np.arange(1,11).reshape(5,2)
np.arange(1,9).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

# Initializing numpy arrays
Initializing a numpy array with one,zero or random numbers or generating numpy array with numbers in linearly equal seprarable range

In [12]:
np.ones((3,2),dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [13]:
np.zeros((3,2,4),dtype=int)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [3]:
np.random.random((2,2))

array([[0.15273532, 0.53413559],
       [0.66867068, 0.61830528]])

In [27]:
np.linspace(1,10,5,dtype=int)

array([ 1,  3,  5,  7, 10])

In [28]:
#generating identity matrix
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

# Array attributes
Every numpy array is an object of numpy class and it has attributes or properties or methods

In [32]:
a1 = np.arange(10)
a2 = np.arange(10).reshape(2,5)
a3 = np.arange(24).reshape(2,3,4)
a3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [30]:
a2.ndim #gives dimension of nd-array

2

## Shape
Shape gives number of elements in each dimension. If applied to a 3d array then it is read from left to right. e.g.(2,3,4), this shows that in every 1d array there are 4 elements and there are 3 1d array or a 2d array of (3,4) and there are total of 2 2d array of (3,4)

In [31]:
a2.shape #number of elements in each dimension
a3.shape

(2, 3, 4)

In [34]:
a3.size #number of elements in array

24

In [35]:
a1.itemsize #number of bytes occupied by each element

4

In [36]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
int32
int32


# Array operations

In [56]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [38]:
a1 + 2 #scalar operations

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [39]:
a2%2==0 #relational operators

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [40]:
#vector operations
a1 * a2 #shape should be same
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [54]:
a1 = np.random.random((2,2))
np.round(a1*100).astype(int)

array([[ 2, 13],
       [26, 27]])

In [57]:
#axis=0 for max item in col and 1 for max in row
print(a1)
print(np.max(a1,axis=0)) #max
print(np.min(a1,axis=0)) #min
print(np.prod(a1,axis=1)) #0 for mult col and 1 for mult row

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 8  9 10 11]
[0 1 2 3]
[   0  840 7920]


In [ ]:
np.sin(a1)

In [58]:
# dot product
print(np.arange(12).reshape(3,4))
print(np.arange(12).reshape(4,3))
np.dot( np.arange(12).reshape(3,4) , np.arange(12).reshape(4,3) )

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [59]:
print(np.ceil([1.2,3.2]))
print(np.floor([1.2,3.2]))

[2. 4.]
[1. 3.]


# Indexing and slicing

In [60]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(27).reshape(3,3,3)
print(f"{a1}\n{a2}\n{a3}")

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [61]:
a1[-1::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [62]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [64]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [65]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# Iterating

In [66]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [67]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
np.transpose(a2)
a2.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [69]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [70]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking
Shape of both arrays should be same

In [71]:
a1 = np.arange(12,24).reshape(3,4)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(27).reshape(3,3,3)
print(f"{a1}\n{a2}\n{a3}")

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [72]:
s1 = np.hstack((a2,a1))
s1

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [73]:
s2 = np.vstack((a2,a1))
s2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting

In [74]:
np.hsplit(s1,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [75]:
np.vsplit(s2,6)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]