In [1]:
import numpy as np

np.sort()

In [18]:
#np.sort -> return a sorted copy of numpy array
a = np.random.randint(1,20,10)
print(a)
np.sort(a)[::-1]

[19 18  4 17 14  2 13  3 15 12]


array([19, 18, 17, 15, 14, 13, 12,  4,  3,  2])

In [21]:
a = np.random.randint(1,100,24).reshape(6,4)
print(a)
np.sort(a,axis=0) #column wise sorting for axis=0

[[19 31 25 12]
 [47 39  5 79]
 [ 5 49 16 26]
 [73 89 66 42]
 [46 67 84 20]
 [50 93 52 62]]


array([[ 5, 31,  5, 12],
       [19, 39, 16, 20],
       [46, 49, 25, 26],
       [47, 67, 52, 42],
       [50, 89, 66, 62],
       [73, 93, 84, 79]])

np.append()

In [20]:
print(a)
np.append(a,10)

[19 18  4 17 14  2 13  3 15 12]


array([19, 18,  4, 17, 14,  2, 13,  3, 15, 12, 10])

In [39]:
print(a)
print(a.shape[0])
np.append(a,np.ones((a.shape[0],1)),axis=1)

[[19 31 25 12]
 [47 39  5 79]
 [ 5 49 16 26]
 [73 89 66 42]
 [46 67 84 20]
 [50 93 52 62]]
6


array([[19., 31., 25., 12.,  1.],
       [47., 39.,  5., 79.,  1.],
       [ 5., 49., 16., 26.,  1.],
       [73., 89., 66., 42.,  1.],
       [46., 67., 84., 20.,  1.],
       [50., 93., 52., 62.,  1.]])

np.concatenate()

In [51]:
a = np.arange(12).reshape(3,4)
b = np.arange(12,24).reshape(3,4)
print(a)
print(b)
print(np.concatenate((a,b),axis=0))
print(np.concatenate((a,b),axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]


np.unique()

In [52]:
a = np.array([1,1,2,2,4,4,5,5,5,5,7,4])
np.unique(a)

array([1, 2, 4, 5, 7])

np.expand_dims()

In [60]:
a = np.random.randint(1,100,12)
print(a)
print(np.expand_dims(a,axis=0))
print(np.expand_dims(a,axis=1))

[19 65 88 66 51 69 30 30  2 59 47 47]
[[19 65 88 66 51 69 30 30  2 59 47 47]]
[[19]
 [65]
 [88]
 [66]
 [51]
 [69]
 [30]
 [30]
 [ 2]
 [59]
 [47]
 [47]]


np.where()

In [69]:
print(a)
np.where(a>50)

[19 65 88 66 51 69 30 30  2 59 47 47]


(array([1, 2, 3, 4, 5, 9], dtype=int64),)

In [81]:
# np.where(condition,true,false)
np.where(a>50,0,a)

array([19,  0,  0,  0,  0,  0, 30, 30,  2,  0, 47, 47])

In [82]:
np.where(a%2==0,-1,a)

array([19, 65, -1, -1, 51, 69, -1, -1, -1, 59, 47, 47])

np.argmax()/np.argmin()

In [86]:
print(a)
np.argmax(a)

[19 65 88 66 51 69 30 30  2 59 47 47]


2

In [91]:
print(b)
np.argmax(b,axis=1)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([3, 3, 3], dtype=int64)

In [93]:
print(a)
np.argmin(a)

[19 65 88 66 51 69 30 30  2 59 47 47]


8

np.cumsum()

In [96]:
print(a)
np.cumsum(a)

[19 65 88 66 51 69 30 30  2 59 47 47]


array([ 19,  84, 172, 238, 289, 358, 388, 418, 420, 479, 526, 573])

In [103]:
print(b)
np.cumsum(b,axis=1)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[12, 25, 39, 54],
       [16, 33, 51, 70],
       [20, 41, 63, 86]])

In [107]:
print(a)
print(np.cumprod(a,dtype=np.int64))
print(b)
print(np.cumprod(b,axis=1,dtype=np.int64))

[19 65 88 66 51 69 30 30  2 59 47 47]
[                 19                1235              108680
             7172880           365816880         25241364720
        757240941600      22717228248000      45434456496000
    2680632933264000  125989747863408000 5921518149580176000]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[    12    156   2184  32760]
 [    16    272   4896  93024]
 [    20    420   9240 212520]]


np.percentile()

In [113]:
print(a)
np.percentile(a,50)

[19 65 88 66 51 69 30 30  2 59 47 47]


49.0

np.histogram()

In [119]:
print(a)
np.histogram(a,bins=[0,20,40,60,80,100])

[19 65 88 66 51 69 30 30  2 59 47 47]


(array([2, 2, 4, 3, 1], dtype=int64), array([  0,  20,  40,  60,  80, 100]))

np.corrcoef()

In [132]:
print(a)
# 1->inversly corelated, 1->corelated linaerly
np.corrcoef([5,2,3,4],[10,3,4,8])

[19 65 88 66 51 69 30 30  2 59 47 47]


array([[1.        , 0.97683083],
       [0.97683083, 1.        ]])

np.isin()

In [141]:
i = [10,20,30,40,51,60,70,80,90,100]
print(a)
print(np.isin(a,i))
print(a[np.isin(a,i)])

[19 65 88 66 51 69 30 30  2 59 47 47]
[False False False False  True False  True  True False False False False]
[51 30 30]


np.flip()

In [150]:
print(b)
print(np.flip(b))
print(np.flip(b,axis=0))

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[23 22 21 20]
 [19 18 17 16]
 [15 14 13 12]]
[[20 21 22 23]
 [16 17 18 19]
 [12 13 14 15]]


np.put()

In [152]:
print(a)
np.put(a,[0,1],[65,19]) # changes the oiginal array
a

[19 65 88 66 51 69 30 30  2 59 47 47]


array([65, 19, 88, 66, 51, 69, 30, 30,  2, 59, 47, 47])

np.delete()

In [159]:
print(a)
np.delete(a,[6,7])

[65 19 88 66 51 69 30 30  2 59 47 47]


array([65, 19, 88, 66, 51, 69,  2, 59, 47, 47])

### Set functions

In [169]:
j=np.arange(5)
k=np.arange(7,12)
print(j,k)
np.union1d(j,k)

[0 1 2 3 4] [ 7  8  9 10 11]


array([ 0,  1,  2,  3,  4,  7,  8,  9, 10, 11])

In [172]:
print(j,k)
np.setdiff1d(j,[2,7,3])

[0 1 2 3 4] [ 7  8  9 10 11]


array([0, 1, 4])

In [173]:
np.setxor1d([2,3,4,5],[3,2,8,9])

array([4, 5, 8, 9])

In [174]:
np.in1d(j,3)

array([False, False, False,  True, False])

np.clip()

In [180]:
print(a)
np.clip(a,a_min=50,a_max=70)

[65 19 88 66 51 69 30 30  2 59 47 47]


array([65, 50, 70, 66, 51, 69, 50, 50, 50, 59, 50, 50])