In [1]:
import numpy as np

###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [69]:
# code here
q1=np.random.randint(0,100,12).reshape(4,3)
q1

array([[33, 92, 97],
       [75, 36,  6],
       [89, 34, 19],
       [53, 64, 69]])

In [70]:
np.sort(q1,axis=0)

array([[33, 34,  6],
       [53, 36, 19],
       [75, 64, 69],
       [89, 92, 97]])

In [71]:
q1a=np.copy(q1)
q1a[:,1]=np.sort(q1[:,1])
q1a

array([[33, 34, 97],
       [75, 36,  6],
       [89, 64, 19],
       [53, 92, 69]])

In [88]:
q1b=np.copy(q1)
ind=np.argsort(np.max(q1b,axis=1))
q1b[ind]

array([[53, 64, 69],
       [75, 36,  6],
       [89, 34, 19],
       [33, 92, 97]])

In [97]:
np.sort(np.ravel(q1)).reshape(q1.shape[0],q1.shape[1])

array([[ 6, 19, 33],
       [34, 36, 53],
       [64, 69, 75],
       [89, 92, 97]])

###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [111]:
# code here
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]
extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
marks=np.array(marks)
extra_subject=np.array(extra_subject)
rec1=np.array(rec1)
rec2=np.array(rec2)
new_marks=np.append(marks,np.expand_dims(extra_subject,axis=1),axis=1)
new_marks

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92]])

In [123]:
new_marks=np.append(np.append(new_marks,np.expand_dims(rec1,axis=0),axis=0) , np.expand_dims(rec2,axis=0) , axis=0)
new_marks

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92],
       [77, 83, 98, 95, 89],
       [92, 71, 52, 61, 53]])

In [127]:
new_marks=np.append(new_marks,np.expand_dims(new_marks.sum(axis=0),axis=0),axis=0)
new_marks

array([[ 13,  10,   9,  33,  41],
       [ 63,  46,  90,  42,  87],
       [ 39,  76,  13,  29,  72],
       [ 82,   9,  29,  78,  36],
       [ 67,  61,  59,  36,  92],
       [ 77,  83,  98,  95,  89],
       [ 92,  71,  52,  61,  53],
       [433, 356, 350, 374, 470]])

In [130]:
new_marks[-1:]=np.sort(new_marks[-1,])
new_marks

array([[ 13,  10,   9,  33,  41],
       [ 63,  46,  90,  42,  87],
       [ 39,  76,  13,  29,  72],
       [ 82,   9,  29,  78,  36],
       [ 67,  61,  59,  36,  92],
       [ 77,  83,  98,  95,  89],
       [ 92,  71,  52,  61,  53],
       [350, 356, 374, 433, 470]])

In [131]:
new_marks[0:2,]

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87]])

###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [134]:
# code here
q4 = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
np.unique(q4,axis=0)

array([[0, 9, 1, 2, 8, 8],
       [1, 2, 3, 3, 1, 1],
       [1, 2, 3, 8, 8, 8]])

In [135]:
np.unique(q4,axis=1)

array([[1, 1, 2, 3, 3],
       [0, 8, 9, 1, 2],
       [1, 8, 2, 3, 8],
       [1, 1, 2, 3, 3]])

###`Q-4:` Flip given 2-D array along both axes at the same time.

In [138]:
# code here
np.flip(q4,axis=0)
np.flip(q4,axis=1)

array([[1, 1, 3, 3, 2, 1],
       [8, 8, 2, 1, 9, 0],
       [8, 8, 8, 3, 2, 1],
       [1, 1, 3, 3, 2, 1]])

### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [166]:
# code here
q5=np.array( [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]] )
q5a=np.where(q5>6,1,0).sum(axis=1)>0
[i for i in range(len(q5a)) if q5a[i]==True]

[1, 3]

 `Q-6:` How to convert an array of arrays into a flat 1d array?


In [167]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [170]:
# code here
np.expand_dims(arr1,axis=0)[0]

array([0, 1, 2])

In [175]:
np.expand_dims(arr2,axis=0)[0]

array([3, 4, 5, 6])

In [176]:
np.expand_dims(arr2,axis=0)[0]

array([3, 4, 5, 6])

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [184]:
# code here
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
np.delete(arr,np.argmax(arr))

array([448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
       387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
       277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
       997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
       645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
       957, 103, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464,
       244, 782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771,
       270, 308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 265, 503,
       320, 230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123, 946,
       587, 227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514, 296,
       879, 575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658, 528,
       395, 525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711, 800,
       976, 786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490, 803,
       621, 453, 193, 607, 677, 637, 728, 724, 534, 748, 291, 19

In [187]:
print(np.min(arr))
np.delete(arr,np.argmin(arr))

103


array([448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
       387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
       277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
       997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
       645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
       957, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464, 244,
       782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771, 270,
       308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 998, 265, 503,
       320, 230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123, 946,
       587, 227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514, 296,
       879, 575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658, 528,
       395, 525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711, 800,
       976, 786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490, 803,
       621, 453, 193, 607, 677, 637, 728, 724, 534, 748, 291, 19

### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [192]:
# code here
np.cumsum(np.sort(np.clip(arr,a_min=1,a_max=200)))

array([  103,   220,   343,   479,   616,   787,   960,  1138,  1319,
        1510,  1703,  1897,  2094,  2294,  2494,  2694,  2894,  3094,
        3294,  3494,  3694,  3894,  4094,  4294,  4494,  4694,  4894,
        5094,  5294,  5494,  5694,  5894,  6094,  6294,  6494,  6694,
        6894,  7094,  7294,  7494,  7694,  7894,  8094,  8294,  8494,
        8694,  8894,  9094,  9294,  9494,  9694,  9894, 10094, 10294,
       10494, 10694, 10894, 11094, 11294, 11494, 11694, 11894, 12094,
       12294, 12494, 12694, 12894, 13094, 13294, 13494, 13694, 13894,
       14094, 14294, 14494, 14694, 14894, 15094, 15294, 15494, 15694,
       15894, 16094, 16294, 16494, 16694, 16894, 17094, 17294, 17494,
       17694, 17894, 18094, 18294, 18494, 18694, 18894, 19094, 19294,
       19494, 19694, 19894, 20094, 20294, 20494, 20694, 20894, 21094,
       21294, 21494, 21694, 21894, 22094, 22294, 22494, 22694, 22894,
       23094, 23294, 23494, 23694, 23894, 24094, 24294, 24494, 24694,
       24894, 25094,

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [200]:
# code here
q9=np.random.random((6))
print(q9)
q9=np.round(q9,decimals=3)
q9

[0.61180952 0.2251835  0.6519617  0.21188297 0.27860815 0.62891927]


array([0.612, 0.225, 0.652, 0.212, 0.279, 0.629])

In [201]:
np.percentile(q9,0)

0.212

In [202]:
np.percentile(q9,100)

0.652

In [203]:
np.percentile(q9,51)

0.46214999999999995

In [204]:
np.percentile(q9,50)

0.4455